# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        Calculadora.setObjectName("Calculadora")
        Calculadora.resize(400, 550)
        self.centralwidget = QtWidgets.QWidget(Calculadora)
        self.centralwidget.setObjectName("centralwidget")
        self.Zero = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.zero()) # type: ignore
        self.Zero.setGeometry(QtCore.QRect(0, 400, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Zero.setFont(font)
        self.Zero.setObjectName("Zero")
        self.Um = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.um()) # type: ignore
        self.Um.setGeometry(QtCore.QRect(0, 300, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Um.setFont(font)
        self.Um.setObjectName("Um")
        self.Tres = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.tres()) # type: ignore
        self.Tres.setGeometry(QtCore.QRect(200, 300, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Tres.setFont(font)
        self.Tres.setObjectName("Tres")
        self.Dois = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dois()) # type: ignore
        self.Dois.setGeometry(QtCore.QRect(100, 300, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Dois.setFont(font)
        self.Dois.setObjectName("Dois")
        self.Quatro = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.quatro()) # type: ignore
        self.Quatro.setGeometry(QtCore.QRect(0, 200, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Quatro.setFont(font)
        self.Quatro.setObjectName("Quatro")
        self.Seis = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.seis()) # type: ignore
        self.Seis.setGeometry(QtCore.QRect(200, 200, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Seis.setFont(font)
        self.Seis.setObjectName("Seis")
        self.Cinco = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.cinco()) # type: ignore
        self.Cinco.setGeometry(QtCore.QRect(100, 200, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Cinco.setFont(font)
        self.Cinco.setObjectName("Cinco")
        self.Sete = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.sete()) # type: ignore
        self.Sete.setGeometry(QtCore.QRect(0, 100, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Sete.setFont(font)
        self.Sete.setAutoFillBackground(False)
        self.Sete.setStyleSheet("")
        self.Sete.setObjectName("Sete")
        self.Nove = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.nove()) # type: ignore
        self.Nove.setGeometry(QtCore.QRect(200, 100, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Nove.setFont(font)
        self.Nove.setObjectName("Nove")
        self.Oito = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.oito()) # type: ignore
        self.Oito.setGeometry(QtCore.QRect(100, 100, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Oito.setFont(font)
        self.Oito.setObjectName("Oito")
        self.Ponto = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.ponto()) # type: ignore
        self.Ponto.setGeometry(QtCore.QRect(100, 400, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.Ponto.setFont(font)
        self.Ponto.setObjectName("Ponto")
        self.Igual = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.igual()) # type: ignore
        self.Igual.setGeometry(QtCore.QRect(200, 400, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Igual.setFont(font)
        self.Igual.setObjectName("Igual")
        self.Dividido = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dividido()) # type: ignore
        self.Dividido.setGeometry(QtCore.QRect(300, 400, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Dividido.setFont(font)
        self.Dividido.setObjectName("Dividido")
        self.Multiplicado = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.multiplicado()) # type: ignore
        self.Multiplicado.setGeometry(QtCore.QRect(300, 300, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Multiplicado.setFont(font)
        self.Multiplicado.setObjectName("Multiplicado")
        self.Menos = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.menos())  # type: ignore
        self.Menos.setGeometry(QtCore.QRect(300, 200, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Menos.setFont(font)
        self.Menos.setObjectName("Menos")
        self.Somado = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.somado())  # type: ignore
        self.Somado.setGeometry(QtCore.QRect(300, 100, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Somado.setFont(font)
        self.Somado.setObjectName("Somado")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 100))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(10)
        self.frame.setObjectName("frame")
        self.Resultado = QtWidgets.QLabel(self.frame)
        self.Resultado.setGeometry(QtCore.QRect(10, 20, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.Resultado.setFont(font)
        self.Resultado.setText("")
        self.Resultado.setObjectName("Resultado")
        Calculadora.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculadora)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        Calculadora.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculadora)
        self.statusbar.setObjectName("statusbar")
        Calculadora.setStatusBar(self.statusbar)

        self.retranslateUi(Calculadora)
        QtCore.QMetaObject.connectSlotsByName(Calculadora)

    def zero(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}0")
    def um(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}1")
    def dois(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}2")
    def tres(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}3")
    def quatro(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}4")
    def cinco(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}5")
    def seis(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}6")
    def sete(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}7")
    def oito(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}8")
    def nove(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}9")
    def ponto(self):
        texto = self.Resultado.text()
        self.Resultado.setText(f"{texto}.")
    def igual(self):
        pass
    def dividido(self):
        pass
    def multiplicado(self):
        pass
    def menos(self):
        pass
    def somado(self):
        global acao
        nums = list()
        nums.append(self.Resultado.text())
        self.Resultado.setText("")
    def retranslateUi(self, Calculadora):
        _translate = QtCore.QCoreApplication.translate
        Calculadora.setWindowTitle(_translate("Calculadora", "Calculadora"))
        self.Zero.setText(_translate("Calculadora", "0"))
        self.Um.setText(_translate("Calculadora", "1"))
        self.Tres.setText(_translate("Calculadora", "3"))
        self.Dois.setText(_translate("Calculadora", "2"))
        self.Quatro.setText(_translate("Calculadora", "4"))
        self.Seis.setText(_translate("Calculadora", "6"))
        self.Cinco.setText(_translate("Calculadora", "5"))
        self.Sete.setText(_translate("Calculadora", "7"))
        self.Nove.setText(_translate("Calculadora", "9"))
        self.Oito.setText(_translate("Calculadora", "8"))
        self.Ponto.setText(_translate("Calculadora", "."))
        self.Igual.setText(_translate("Calculadora", "="))
        self.Dividido.setText(_translate("Calculadora", "/"))
        self.Multiplicado.setText(_translate("Calculadora", "*"))
        self.Menos.setText(_translate("Calculadora", "-"))
        self.Somado.setText(_translate("Calculadora", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QMainWindow()
    ui = Ui_Calculadora()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())
