# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designs/BemVindo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BemVindo(object):
    def setupUi(self, BemVindo):
        BemVindo.setObjectName("BemVindo")
        BemVindo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BemVindo)
        self.centralwidget.setObjectName("centralwidget")
        self.Saudacao = QtWidgets.QLabel(self.centralwidget)
        self.Saudacao.setGeometry(QtCore.QRect(80, 70, 621, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Saudacao.setFont(font)
        self.Saudacao.setTextFormat(QtCore.Qt.AutoText)
        self.Saudacao.setAlignment(QtCore.Qt.AlignCenter)
        self.Saudacao.setObjectName("Saudacao")
        self.Comecar = QtWidgets.QPushButton(self.centralwidget)
        self.Comecar.setGeometry(QtCore.QRect(300, 340, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Comecar.setFont(font)
        self.Comecar.setObjectName("Comecar")
        BemVindo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BemVindo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        BemVindo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BemVindo)
        self.statusbar.setObjectName("statusbar")
        BemVindo.setStatusBar(self.statusbar)

        self.retranslateUi(BemVindo)
        QtCore.QMetaObject.connectSlotsByName(BemVindo)

    def retranslateUi(self, BemVindo):
        _translate = QtCore.QCoreApplication.translate
        BemVindo.setWindowTitle(_translate("BemVindo", "MainWindow"))
        self.Saudacao.setText(_translate("BemVindo", "Seja Bem Vindo ao Programmers Interface"))
        self.Comecar.setText(_translate("BemVindo", "Continuar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BemVindo = QtWidgets.QMainWindow()
    ui = Ui_BemVindo()
    ui.setupUi(BemVindo)
    BemVindo.show()
    sys.exit(app.exec_())
